//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Przewodnik.Content.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Przewodnik.Content.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fontanna działa sezonowo - od początku maja do końca października.\nPołożona w malowniczym parku Szczytnickim, otoczona pergolą i w bezpośrednim sąsiedztwie Hali Stulecia, multimedialna wrocławska fontanna jest największym tego typu obiektem w Polsce i jednym z największych w Europie. Otwarta została 4 czerwca 2009 z okazji 20. rocznicy wolnych wyborów. Jej powierzchnia wynosi ok. 1 hektara. W fontannie zainstalowano prawie 300 dysz, z których tryska woda w formie gejzerów, mgiełki, piany itp. na wysokość n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_FONTANNA_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_FONTANNA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fontanna multimedialna.
        /// </summary>
        internal static string A_FONTANNA_TITLE {
            get {
                return ResourceManager.GetString("A_FONTANNA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hala Stulecia uznawana za jedno z najważniejszych dzieł w architekturze światowej XX w.\nZaprojektowana przez wybitnego miejskiego architekta Maxa Berga. Powstała w 1913 r. z okazji międzynarodowej wystawy w stulecie bitwy pod Lipskiem. W 2006 r. obiekt wpisano na Listę Światowego Dziedzictwa UNESCO. W Hali odbywają się imprezy sportowe o charakterze lokalnym, krajowym jak i międzynarodowym..
        /// </summary>
        internal static string A_HALA_STULECIA_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_HALA_STULECIA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hala stulecia.
        /// </summary>
        internal static string A_HALA_STULECIA_TITLE {
            get {
                return ResourceManager.GetString("A_HALA_STULECIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogród Botaniczny Uniwersytetu Wrocławskiego, nazywany oazą piękna i spokoju w sercu wielkiego miasta, to żywe muzeum, a zarazem ośrodek naukowy i dydaktyczny oraz ulubione miejsce wypoczynku wrocławian. Położony jest po północnej stronie katedry Św. Jana Chrzciciela i kościoła Św.Krzyża, częściowo w obrębie historycznego Ostrowa Tumskiego, w odległości ok. 2 km od Rynku. Jest drugim (po ogrodzie krakowskim ) najstarszym tego typu ogrodem w Polsce, wpisanym na listę zabytków woj. dolnośląskiego i mieszczącym [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_OGROD_BOTANICZNY_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_OGROD_BOTANICZNY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ogród botaniczny.
        /// </summary>
        internal static string A_OGROD_BOTANICZNY_TITLE {
            get {
                return ResourceManager.GetString("A_OGROD_BOTANICZNY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Największy i najstarszy w mieście, został założony w 1785 r. jako prywatny ogród w majątku Stare Szczytniki.\nGłówną atrakcją parku jest powstały w 1913 r., a później wielokrotnie odbudowywany Ogród Japoński. Przygotowany i urządzony przez największego wówczas japonistę - entuzjastę, hrabiego Fritza von Hochberga, przy udziale japońskiego ogrodnika Mankichi Arai - był perłą wystawy. Po ekspozycji zabrano jednak liczne, wypożyczone na czas wystawy, detale (decydujące o japońskości założenia ogrodu). Od 1996  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_OGROD_JAPONSKI_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_OGROD_JAPONSKI_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ogród japoński.
        /// </summary>
        internal static string A_OGROD_JAPONSKI_TITLE {
            get {
                return ResourceManager.GetString("A_OGROD_JAPONSKI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najstarszą częścią Wrocławia jest Ostrów Tumski.\nOtoczony wodami Odry dawny gród, który dał początek miastu, mieści wspaniałe zabytki architektoniczne. Najokazalsze z nich to odbudowane po wojennych zniszczeniach gotycka katedra św. Jana Chrzciciela oraz kościół Świętego Krzyża. Znajduje się tu również Muzeum Archidiecezjalne, będące najstarszą, zachowującą ciągłość historyczną placówką muzealną we Wrocławiu – od ponad 100 lat gromadzi ono zabytki sztuki sakralnej, które, wycofane z użytku kultowego, posia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_OSTROW_TUMSKI_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_OSTROW_TUMSKI_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ostrów tumski.
        /// </summary>
        internal static string A_OSTROW_TUMSKI_TITLE {
            get {
                return ResourceManager.GetString("A_OSTROW_TUMSKI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pałac Królewski ulokowany jest w południowej części historycznego Starego Miasta we Wrocławiu, przy ulicy Kazimierza Wielkiego, w obszarze zwanym dziś Dzielnicą Czterech Wyznań.\nPoczątki pałacu sięgają początku XVIII w. Obecnie odrestaurowany Pałac Królewski stanowi jeden z najważniejszych zabytków Wrocławia oraz centrum wystawiennicze, gdzie w przestronnych salach prezentowana jest wystawa „1000 lat Wrocławia”.\nMuzeum Historyczne gromadzi i udostępnia zabytki z zakresu historii i sztuki dotyczące dziejów [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_PALAC_KROLEWSKI_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_PALAC_KROLEWSKI_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pałac królewski.
        /// </summary>
        internal static string A_PALAC_KROLEWSKI_TITLE {
            get {
                return ResourceManager.GetString("A_PALAC_KROLEWSKI_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panorama Racławicka”, oddział Muzeum Narodowego we Wrocławiu, jest miejscem szczególnie godnym zobaczenia.\n„Panorama Racławicka”, oddział Muzeum Narodowego we Wrocławiu, jest miejscem szczególnie godnym zobaczenia. Unikatowe płótno o wymiarach 120x15 m jest dziełem zespołu malarzy pod kierownictwem J. Styki i W. Kossaka. Obraz powstał we Lwowie w 1894 roku. We Wrocławiu został udostępniony 14 czerwca 1985 roku. Seanse odbywają się co pół godziny..
        /// </summary>
        internal static string A_PANORAMA_RACLAWICKA_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_PANORAMA_RACLAWICKA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to panorama racławicka.
        /// </summary>
        internal static string A_PANORAMA_RACLAWICKA_TITLE {
            get {
                return ResourceManager.GetString("A_PANORAMA_RACLAWICKA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jest sercem Wrocławia, tętniącym życiem o każdej porze dnia i nocy.\nNależy do największych założeń urbanistycznych tego typu w Europie. W jego centrum znajdują się Sukiennice i gmach ratusza, który jest zabytkiem architektury gotyckiej i renesansowej. Na szczycie 66-metrowej wieży znajduje się najstarszy wizerunek herbu miasta, stworzony w połowie XVI w. Przed wschodnią fasadą ratusza stoi pręgierz (kopia średniowiecznego, zniszczonego w 1945 r.), przed zachodnią - pomnik Aleksandra Fredry przeniesiony ze  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_RYNEK_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_RYNEK_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rynek.
        /// </summary>
        internal static string A_RYNEK_TITLE {
            get {
                return ResourceManager.GetString("A_RYNEK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyspa Słodowa we Wrocławiu - niewielka wysepka na Odrze w obrębie wrocławskiego Starego Miasta, w sąsiedztwie mniejszych nieco od niej Wyspy Bielarskiej i Wyspy Młyńskiej.\nWyspa Słodowa jest ulubionym miejscem wypoczynku dla Wrocławian i tłumnie odwiedzane przez turystów. Imponujące sąsiedztwo zespołu wysp, położonych w historycznie najstarszej części miasta, przesądza o atrakcyjności tego miejsca. Co roku urządza się tutaj majówki i studenckie imprezy związane z hucznymi obchodami Juwenaliów. Podczas waka [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_WYSPA_SLODOWA_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_WYSPA_SLODOWA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyspa słodowa.
        /// </summary>
        internal static string A_WYSPA_SLODOWA_TITLE {
            get {
                return ResourceManager.GetString("A_WYSPA_SLODOWA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misją wrocławskiego ZOO jest zachowanie różnorodności biologicznej w trosce o pełnowartościowy rozwój przyszłych pokoleń.\nWrocławski Ogród Zoologiczny na 33 ha powierzchni tworzy atrakcyjne, tematyczne ekspozycje fauny poszczególnych kontynentów (Pawilon Madagaskaru, Sahara, wybieg niedźwiedzi brunatnych, basen płetwonogich). Daje schronienie 4500 zwierzętom ponad 800 gatunków, w tym zagrożonym wyginięciem, a nawet nie występującym już w naturalnym środowisku. Trwa budowa kompleksu ekspozycji środowisk wod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A_ZOO_DESCRIPTION {
            get {
                return ResourceManager.GetString("A_ZOO_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOO.
        /// </summary>
        internal static string A_ZOO_TITLE {
            get {
                return ResourceManager.GetString("A_ZOO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atrakcje.
        /// </summary>
        internal static string B_atrakcje {
            get {
                return ResourceManager.GetString("B_atrakcje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centrum.
        /// </summary>
        internal static string B_centrum {
            get {
                return ResourceManager.GetString("B_centrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotele.
        /// </summary>
        internal static string B_hotele {
            get {
                return ResourceManager.GetString("B_hotele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kina.
        /// </summary>
        internal static string B_kina {
            get {
                return ResourceManager.GetString("B_kina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kościoły.
        /// </summary>
        internal static string B_koscioly {
            get {
                return ResourceManager.GetString("B_koscioly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muzea.
        /// </summary>
        internal static string B_muzea {
            get {
                return ResourceManager.GetString("B_muzea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parki.
        /// </summary>
        internal static string B_parki {
            get {
                return ResourceManager.GetString("B_parki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teatry.
        /// </summary>
        internal static string B_teatry {
            get {
                return ResourceManager.GetString("B_teatry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transport.
        /// </summary>
        internal static string B_transport {
            get {
                return ResourceManager.GetString("B_transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urzędy.
        /// </summary>
        internal static string B_urzedy {
            get {
                return ResourceManager.GetString("B_urzedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zakupy.
        /// </summary>
        internal static string B_zakupy {
            get {
                return ResourceManager.GetString("B_zakupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzin temu.
        /// </summary>
        internal static string DT_godzin_temu {
            get {
                return ResourceManager.GetString("DT_godzin_temu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godzinę temu.
        /// </summary>
        internal static string DT_godzine_temu {
            get {
                return ResourceManager.GetString("DT_godzine_temu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godziny temu.
        /// </summary>
        internal static string DT_godziny_temu {
            get {
                return ResourceManager.GetString("DT_godziny_temu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minut temu.
        /// </summary>
        internal static string DT_minut_temu {
            get {
                return ResourceManager.GetString("DT_minut_temu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutę temu.
        /// </summary>
        internal static string DT_minute_temu {
            get {
                return ResourceManager.GetString("DT_minute_temu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minuty temu.
        /// </summary>
        internal static string DT_minuty_temu {
            get {
                return ResourceManager.GetString("DT_minuty_temu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie aktualnych wydarzeń.
        /// </summary>
        internal static string LOAD_events {
            get {
                return ResourceManager.GetString("LOAD_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicjalizacja....
        /// </summary>
        internal static string LOAD_init {
            get {
                return ResourceManager.GetString("LOAD_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie zdjęć z Instagrama.
        /// </summary>
        internal static string LOAD_instagram {
            get {
                return ResourceManager.GetString("LOAD_instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie map.
        /// </summary>
        internal static string LOAD_maps {
            get {
                return ResourceManager.GetString("LOAD_maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie aktualnych twittów.
        /// </summary>
        internal static string LOAD_twitter {
            get {
                return ResourceManager.GetString("LOAD_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdzanie frontów atmosferycznych.
        /// </summary>
        internal static string LOAD_weather {
            get {
                return ResourceManager.GetString("LOAD_weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atrakcje turystyczne.
        /// </summary>
        internal static string M_atrakcje_turystyczne {
            get {
                return ResourceManager.GetString("M_atrakcje_turystyczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niezbędnik każdego turysty, czyli co warto zobaczyć i zwiedzić we Wrocławiu.
        /// </summary>
        internal static string M_atrakcje_turystyczne_description {
            get {
                return ResourceManager.GetString("M_atrakcje_turystyczne_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plan miasta.
        /// </summary>
        internal static string M_plan_miasta {
            get {
                return ResourceManager.GetString("M_plan_miasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.
        /// </summary>
        internal static string M_twitter {
            get {
                return ResourceManager.GetString("M_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to widokówka.
        /// </summary>
        internal static string M_widokowka {
            get {
                return ResourceManager.GetString("M_widokowka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wydarzenia.
        /// </summary>
        internal static string M_wydarzenia {
            get {
                return ResourceManager.GetString("M_wydarzenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak wydarzeń dla wybranej kategorii.
        /// </summary>
        internal static string W_brak_wydarzen {
            get {
                return ResourceManager.GetString("W_brak_wydarzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzieci.
        /// </summary>
        internal static string W_dzieci {
            get {
                return ResourceManager.GetString("W_dzieci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inne.
        /// </summary>
        internal static string W_inne {
            get {
                return ResourceManager.GetString("W_inne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kino.
        /// </summary>
        internal static string W_kino {
            get {
                return ResourceManager.GetString("W_kino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muzyka.
        /// </summary>
        internal static string W_muzyka {
            get {
                return ResourceManager.GetString("W_muzyka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nauka.
        /// </summary>
        internal static string W_nauka {
            get {
                return ResourceManager.GetString("W_nauka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sport.
        /// </summary>
        internal static string W_sport {
            get {
                return ResourceManager.GetString("W_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teatr.
        /// </summary>
        internal static string W_teatr {
            get {
                return ResourceManager.GetString("W_teatr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wszystkie.
        /// </summary>
        internal static string W_wszystkie {
            get {
                return ResourceManager.GetString("W_wszystkie", resourceCulture);
            }
        }
    }
}
